version: 2.0
jobs:
  build:
    working_directory: ~/datahike

    docker:
      - image: circleci/clojure:lein-2.9.3
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: alice
          POSTGRES_PASSWORD: foo
          POSTGRES_DB: config-test

    filters:
      branches:
        only:
          - master
          - development

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - datahike-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: datahike-{{ checksum "project.clj" }}
      - run: ./bin/run-unit-tests
      - run: lein uberjar
      - run: ./bin/run-integration-tests
